### ISSUE TITLE
Sponsors page: text is right aligned and does not fill screen on mobile

### ISSUE THREAD

**Issue by JemmaD** [OpenSecuritySummit/oss2019#36]
Text is right aligned and does not fill screen on mobile

**Comment by fzipi** [comment]
Mobile: https://open-security-summit.org/sponsors/

**Comment by fzipi** [comment]
@JemmaDSmith What do you mean it is "right aligned"? Could you please add an image to illustrate this?

**Comment by fzipi** [comment]
@JemmaDSmith Ping?

**Comment by JemmaD** [comment]
clearly got left and right mixed up when i wrote this one
![image from ios](https://user-images.githubusercontent.com/34240078/52777306-5ba11d80-303b-11e9-9244-d3c37890accf.png)
