### ISSUE TITLE
Can someone please copy the outcomes structure across from oss2018?

### ISSUE THREAD

**Issue by Ambg05** [OpenSecuritySummit/oss2019#361]
I've tried but am worried I will end up making a MESS.  We need the 'tracks/track-theme/Working-sessions/user-sessions' copied over from 2018 so it will be easier for organisers & participants to add content themselves where they are happy to do so, and easier for Robert & I (& everyone) to see what's what. Many thanks!

**Comment by fzipi** [comment]
@Ambg05 We are going to use a different way for handling out the outcomes.
We are going to use a google forms for uploading the outcomes, and then create a small slides for each one.

**Comment by fzipi** [comment]
Please @Ambg05 ping me by slack or again here if you need something else. I'm closing this one.
