### ISSUE TITLE
Update slack link in footer with new invite link

### ISSUE THREAD

**Issue by JemmaD** [OpenSecuritySummit/oss2019#37]
Currently no new slackers can join workspace

**Comment by fzipi** [comment]
Seems like I don't have privileges for that. Neither the app nor the website allows me to do that. Can someone (@DinisCruz , @SebaDele , @devseccon ?) [do this procedure](https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link-) and paste the link here?
