### ISSUE TITLE
Delete 2018 content

### ISSUE THREAD

**Issue by bkimminich** [OpenSecuritySummit/oss2019#41]
It seems there is still a lot of tracks and session from 2018 in this repository. Are these all tracks known to "rinse & repeat" their sessions from last year? I found one old Juice Shop session where this is not the case and deleted it - along with adding my 2019 ideas - in #40.

Without some housekeeping we might end up with confused or disappointed participants because it might turn out that their favorite session was only a zombie from last year.

**Suggestion:**
1. Send email to all known participants for 2019 to update their planned tracks, sessions and teams within 1 week
2. After 1 week delete all track, team and session files with last update timestamp >1 week

It's a bit harsh, but it should create a clean state. And even if someone loses their data, they can always get it back from Git history.

**Comment by fzipi** [comment]
@JemmaDSmith What do you think about this? I think most tracks/sessions were included by Dinis.

**Comment by JemmaD** [comment]
@DinisCruz can you confirm you are happy with this?

**Comment by bkimminich** [comment]
Hi all, if we don't bring out the :wastebasket: now we probably never will before the summit ... I'm still convinced that we could advertise the summit much better when starting with a clean slate schedule...

**Comment by bkimminich** [comment]
Also, if you want to keep the "One Slack channel per session/track/..." approach from last year, wouldn't it be good to archive the old channels now to be able to "start clean" and avoid having people join the wrong channels?

**Comment by fzipi** [comment]
@SebaDele , @devseccon Comments?

**Comment by FrancoisRaynaud** [comment]
we do need to cleanup for sure, although the aim from @DinisCruz to populate the site with this info, was right to show progress. @bkimminich are you ok to do a  gradual cleanup?

**Comment by FrancoisRaynaud** [comment]
agreed for the slack channel, they should be marked as 2018 content to ensure we don't get confused

**Comment by bkimminich** [comment]
How is the Slack and Schedule cleanup doing?

**Comment by clazba** [comment]
Track specific slack channels should be used for scheduling and sessions content so to avoid overlap. There is merit is scheduling sessions that have related content sequentially. e.g. "automating ZAP" should come before "dealing with ZAP findings" - been posting to #oss-schedule but channel seems dormant

**Comment by DinisCruz** [comment]
Yes delete anything that doesn't make sense

Ideally (if possible) tell the people affected and nudge them to create a better version for this year

**Comment by DinisCruz** [comment]
@bkimminich go for it (let's get some quality into those sessions)

@fzipi those sessions were added so that the Summit didn't look empty :)

**Comment by SebaDele** [comment]
ok4me!

**Comment by DinisCruz** [comment]
has this been done?

**Comment by bkimminich** [comment]
I can't really tell, but the number of completely content-free session pages somewhat indicates the opposite.

**Comment by bkimminich** [comment]
Kudos to @DinisCruz for 🧹ing up! 👍
