### ISSUE TITLE
Ambiguity conflict between equally names tracks and teams

### ISSUE THREAD

**Issue by bkimminich** [OpenSecuritySummit/oss2019#46]
![image](https://user-images.githubusercontent.com/3531020/52698863-b6237680-2f74-11e9-8d5f-48df31700340.png)

Having a team with the same name as a track will make some (or maybe even all) generated links go to the team instead of the track.

Workaround: Do not use identical names for tracks and teams, duh! :grinning:

**Comment by fzipi** [comment]
I think that it is a bug in the teams partial.

**Comment by fzipi** [comment]
Well, I can't reproduce that [in production](https://open-security-summit.org/tracks/owasp-juice-shop/user-sessions/juice-shop-contributor-onboarding/). Links are generated using the `type:` in the front matter. So it should generate the correct one if the type is `track` or `team`. 

@bkimminich Could you provide more info about it?

**Comment by bkimminich** [comment]
I deleted the team `OWASP Juice Shop` until this gets fixed. If you create any team with the same name as an existing track you should experience this issue.

**Comment by fzipi** [comment]
Will try using that, thx.

**Comment by fzipi** [comment]
Could you please add again your team? Thanks!

**Comment by bkimminich** [comment]
Done, PR is up!

**Comment by bkimminich** [comment]
Still not fixed. Try going to https://open-security-summit.org/tracks/owasp-juice-shop/working-sessions/juice-shop-hackathon2/ and then click the "Track" link to "OWASP Juice Shop". It will send you to https://open-security-summit.org/teams/owasp_juiceshop/ instead of expected https://open-security-summit.org/tracks/owasp_juiceshop/.

**Comment by fzipi** [comment]
Weird. It doesn't...?

**Comment by bkimminich** [comment]
I guess Hugo doesn't know the difference between types. If you create a participant named "OWASP Juice Shop" I'm pretty sure link will all go there as its alphabetically seen first by Hugo... Just a wild guess... 🤔

**Comment by fzipi** [comment]
Well, it's not hugo, is how we use it :(
That specific step is generic, so we weren't checking the document's type. But I think we should rewrite it.

Will create a new issue with the generic problem, so we can think in a more generic solution.
