### ISSUE TITLE
Using title only for finding pages has side effects

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2019#51]
I've had seen this the previous edition, for example, with outcomes (that had the same title as the working session). But now has happened with teams (See #46 ), and as @bkimminich says, it could happen with others.

We need to have a better approach for this.

**Comment by bkimminich** [comment]
Is this still an issue? If it is not solvable, we should somehow prevent name duplicates - maybe check for those in the CI build or something?

**Comment by oss-bot-dinis** [comment]
so all titles should be unique (there is already a python notebook cell that checks for it (which needs to be moved to a CI build test))

the Teams workflow needs to be changed (to use data from the user's page and not from the 'teams' pages)
