### ISSUE TITLE
Slack channels for Juice Shop track

### ISSUE THREAD

**Issue by bkimminich** [OpenSecuritySummit/oss2019#57]
Please create the following channels for the Juice Shop track
* [x] `t-owasp-juiceshop`
* [x] `u-juiceshop-101`
* [x] `u-juiceshop-contrib-onboard`
* [x] `u-juiceshop-round-table`
* [x] `u-juiceshop-release-night`
* [x] `w-juiceshop-chall-refactor`
* [x] `w-juiceshop-hack-n-code` (one channel for the _Juice Shop Hack'n'Code I_, _II_, _III_ and _IV_ sessions)

**Comment by fzipi** [comment]
@JemmaDSmith Who is able to create these channels in Slack?

**Comment by PathDependence** [comment]
Was this answered elsewhere? @JemmaDSmith @bkimminich ?

**Comment by bkimminich** [comment]
No, not that I'm aware of. But I didn't check the OSS Slack for a few days.

**Comment by JemmaD** [comment]
Channels created

**Comment by fzipi** [comment]
Closing. Thanks @JemmaDSmith !
