### ISSUE TITLE
Webpage still shows 2018 in search engines

### ISSUE THREAD

**Issue by tashjnorris** [OpenSecuritySummit/oss2019#99]
when searching for the Open Security Summit the web page title preview shows 2018 as the date.

**Comment by DinisCruz** [comment]
yap

![image](https://user-images.githubusercontent.com/656739/57216382-a2bdff80-6fe7-11e9-8490-4a506aacc04d.png)

humm. I'm not sure where Google is getting that from (there are no mentions of that text in the code)

Anyway I've changed the title to 2019

![image](https://user-images.githubusercontent.com/656739/57216484-dd279c80-6fe7-11e9-8440-c32674983620.png)

**Comment by fzipi** [comment]
Seems to be working now. Closing.
